### ISSUE TITLE
Camera showing a Green/Purple line on top of every photo

### ISSUE THREAD

**Issue by GianniDPC** [nobodyAtall/msm7x30-3.4.x-nAa#1]
If I open up the Camera app and use 5 MP picture size and then take a picture you can see a green line on top of every photo. Preview: http://i.imgur.com/L5Hvfyd.jpg?1

**Comment by nobodyAtall** [comment]
Thanks, this is a known issue that needs looking into.

**Comment by nobodyAtall** [comment]
This is now fixed
