### ISSUE TITLE
Touch sensor bug

### ISSUE THREAD

**Issue by dbodyas** [nobodyAtall/msm7x30-3.4.x-nAa#3]
I'm using [CM10.1](http://goo.im/devs/shufuking/CM10.1/Build%2020130515)  on ArcS ( _LT18i 4.1.B.0.587 (1254-2716)_ )  (there is no problems with cm10 and kernel v2.6).
My touch is on the center of the screen
At the right side of the screen are phantom touches
Also here is [link to video preview](http://youtu.be/-U5yXlQQ9Hs) / [mirror](http://d.pr/v/292d) (sorry for bad quality)
![screenshot_2013-05-16-20-58-59](https://f.cloud.github.com/assets/1251682/514392/495dff3c-be57-11e2-86e1-11b58345db6a.png)

**Comment by n1kolaa** [comment]
its fixed on cm10.2 and cm10.1 :+1:

**Comment by mikeNG** [comment]
@n1kolaa so undervolting solved this issue?

**Comment by n1kolaa** [comment]
https://github.com/LegacyXperia/msm7x30-3.4.x-nAa/commit/23a38770089c08675f325a9249e1f44896159e5d
and this
https://github.com/LegacyXperia/msm7x30-3.4.x-nAa/commit/e02e5cfeda139079f147d310f6020fe6a75679e1
YEP
